// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xprvdwevpgzoksmlatqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwcnZkd2V2cGd6b2tzbWxhdHFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNzE4MzYsImV4cCI6MjA2OTY0NzgzNn0.8hFq6ScmQYgEpKl28ieYVxjky4obP9oLfHX4oX8xhsg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});